PMSAWebMVC/Models/PurchaseOrderReceive.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSAWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderReceive
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrderReceive()
        {
            this.PurchaseOrderReceiveDtl = new HashSet<PurchaseOrderReceiveDtl>();
            this.StockIn = new HashSet<StockIn>();
        }
    
        public int PurchaseOrderReceiveOID { get; set; }
        public string PurchaseOrderReceiveID { get; set; }
        public string PurchaseOrderID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public string PurchaseEmployeeID { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierAccountID { get; set; }
        public string SignStatus { get; set; }
        public Nullable<int> SignFlowOID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual SignFlow SignFlow { get; set; }
        public virtual SupplierAccount SupplierAccount { get; set; }
        public virtual SupplierInfo SupplierInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderReceiveDtl> PurchaseOrderReceiveDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockIn> StockIn { get; set; }
    }
}

PMSAWebMVC/Controllers/PurchaseOrderReceivesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PMSAWebMVC.Models;

namespace PMSAWebMVC.Controllers
{
    public class PurchaseOrderReceivesController : Controller
    {
        private PMSAEntities db = new PMSAEntities();

        // GET: PurchaseOrderReceives
        public ActionResult Index()
        {
            var purchaseOrderReceive = db.PurchaseOrderReceive.Include(p => p.Employee).Include(p => p.PurchaseOrder).Include(p => p.SignFlow).Include(p => p.SupplierAccount).Include(p => p.SupplierInfo);
            return View(purchaseOrderReceive);
        }

        //進貨明細
        public ActionResult IndexDtl(string id)
        {
            var purchaseOrderReceiveDtl = db.PurchaseOrderReceiveDtl.Where(w=>w.PurchaseOrderReceiveID == id).Include(p => p.PurchaseOrderDtl).Include(p => p.PurchaseOrderReceive);
            return View(purchaseOrderReceiveDtl);
        }

        // GET: PurchaseOrderReceives/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PurchaseOrderReceive purchaseOrderReceive = db.PurchaseOrderReceive.Find(id);
            if (purchaseOrderReceive == null)
            {
                return HttpNotFound();
            }
            var da = db.PurchaseOrderReceive.Where(w => w.PurchaseOrderReceiveID == id).Select(s => s.SignStatus).ToList();
            StockInsController stock = new StockInsController();
            string datastust = stock.stut(da[0]);

            var dat = db.PurchaseOrderReceive.Where(w => w.PurchaseOrderReceiveID == id).Select(s => s.PurchaseDate).ToList();
            var date = dat[0].ToShortDateString();

            var emid = db.PurchaseOrderReceive.Where(w => w.PurchaseOrderReceiveID == id).Select(s => new { s.PurchaseEmployeeID, s.Employee.Name }).ToList();
            var emid1 = emid[0].PurchaseEmployeeID + "-" + emid[0].Name;

            var supid = db.PurchaseOrderReceive.Where(w => w.PurchaseOrderReceiveID == id).Select(s => new { s.SupplierAccountID, s.SupplierAccount.ContactName }).ToList();
            var supid1 = supid[0].SupplierAccountID + "-" + supid[0].ContactName;

            var scode = db.PurchaseOrderReceive.Where(w => w.PurchaseOrderReceiveID == id).Select(s => new { s.SupplierCode, s.SupplierInfo.SupplierName }).ToList();
            var scode1 = scode[0].SupplierCode + "-" + scode[0].SupplierName;

            var datas = db.PurchaseOrderReceive.AsEnumerable().Where(w => w.PurchaseOrderReceiveID == id).
                        Select(s => new
                        {
                            s.PurchaseOrderReceiveID,
                            s.PurchaseOrderID,
                            date,
                            emid1,
                            s.PurchaseEmployeeID,
                            scode1,
                            s.SupplierAccountID,
                            supid1,
                            s.SupplierCode,
                            datastust
                        });

            return Json(datas, JsonRequestBehavior.AllowGet);
        }
        
        // create
        DateTime now = DateTime.Now;
        public void Create(string shipid)
        {
            PurchaseOrderReceive purchaseOrderReceive = new PurchaseOrderReceive();
            //PurchaseOrderReceiveID
            string porId = $"POR-{now:yyyyMMdd}-";
            int count = db.PurchaseOrderReceive.Where(x => x.PurchaseOrderReceiveID.StartsWith(porId)).Count();
            count++;
            porId = $"{porId}{count:000}";
            purchaseOrderReceive.PurchaseOrderReceiveID = porId;
            //PurchaseOrderID
            var poid = db.ShipNotice.Where(w => w.ShipNoticeID == shipid).Select(s => s.PurchaseOrderID).ToList();
            var poid1 = poid[0];
            purchaseOrderReceive.PurchaseOrderID = poid1;
            //PurchaseDate
            purchaseOrderReceive.PurchaseDate = now;
            //PurchaseEmployeeID
            var pemid = db.ShipNotice.Where(w => w.ShipNoticeID == shipid).Select(s => s.EmployeeID).ToList();
            string pemid1 = pemid[0];
            purchaseOrderReceive.PurchaseEmployeeID = pemid1;
            //SupplierCode
            var supcode = db.ShipNotice.Where(w => w.ShipNoticeID == shipid).Select(s => s.SupplierAccount.SupplierCode).ToList();
            string supcode1 = supcode[0];
            purchaseOrderReceive.SupplierCode = supcode1;
            //SupplierAccountID
            var supid = db.ShipNotice.Where(w => w.ShipNoticeID == shipid).Select(s => s.SupplierAccountID).ToList();
            string supid1 = supid[0];
            purchaseOrderReceive.SupplierAccountID = supid1;
            //SignStatus
            purchaseOrderReceive.SignStatus = "S";
            if (ModelState.IsValid)
            {
                db.PurchaseOrderReceive.Add(purchaseOrderReceive);
                db.SaveChanges();
                //呼叫新增進貨單明細方法
                PurchaseOrderReceiveDtlsController purchaseOrderReceiveDtlsController = new PurchaseOrderReceiveDtlsController();
                purchaseOrderReceiveDtlsController.Create(shipid, porId);
            }
        }

        // GET: PurchaseOrderReceives/Edit/5
        //public ActionResult Edit(string id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    PurchaseOrderReceive purchaseOrderReceive = db.PurchaseOrderReceive.Find(id);
        //    if (purchaseOrderReceive == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    ViewBag.PurchaseEmployeeID = new SelectList(db.Employee, "EmployeeID", "Name", purchaseOrderReceive.PurchaseEmployeeID);
        //    ViewBag.PurchaseOrderID = new SelectList(db.PurchaseOrder, "PurchaseOrderID", "SupplierCode", purchaseOrderReceive.PurchaseOrderID);
        //    ViewBag.SignFlowOID = new SelectList(db.SignFlow, "SignFlowOID", "OriginatorID", purchaseOrderReceive.SignFlowOID);
        //    ViewBag.SupplierAccountID = new SelectList(db.SupplierAccount, "SupplierAccountID", "ContactName", purchaseOrderReceive.SupplierAccountID);
        //    ViewBag.SupplierCode = new SelectList(db.SupplierInfo, "SupplierCode", "SupplierName", purchaseOrderReceive.SupplierCode);
        //    return View(purchaseOrderReceive);
        //}

        //// POST: PurchaseOrderReceives/Edit/5
        //// 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        //// 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        public ActionResult Edit(PurchaseOrderReceive purchaseOrderReceive)
        {
            string message = "修改成功!!";
            bool status = true;
            if (ModelState.IsValid)
            {
                StockInsController stock = new StockInsController();
                string stu = purchaseOrderReceive.SignStatus;
                string datastust = stock.stut(stu);
                string poid = purchaseOrderReceive.PurchaseOrderReceiveID;
                var q = purchaseOrderReceive;
                db.Entry(purchaseOrderReceive).State = EntityState.Modified;
                db.SaveChanges();

                //判斷是否有此筆入庫單
                //var datas = db.StockIn.Where(w => w.PurchaseOrderReceiveID == poid).Select(s => s.StockInID).ToList();
                //if (datas != null&&datas[0].Count() > 0)
                //{
                //    string ss = datas[0];
                //    this.stockinstatus(ss, stu);
                //}

                return Json(new { status = status, message = message, id = db.PurchaseOrderReceive.Max(x => x.PurchaseOrderReceiveOID), datastust }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                message = "修改失敗!!";
                status = false;
                return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
            }
        }

        public void stockinstatus(string oid, string stu)
        {
            StockIn stockIn = new StockIn();
            var stockdata = db.StockIn.Where(w => w.StockInID == oid).Select(s => new
            {
                s.PurchaseOrderReceiveID,
                s.AddStockDate,
                s.CreateDate,
                s.CreateEmployeeID,
                s.Remark
            }).ToList();
            //$("#StockInID").val(datas[0].StockInID);
            stockIn.StockInID = oid;
            //    $("#PurchaseOrderReceiveID").val(datas[0].PurchaseOrderReceiveID);
            stockIn.PurchaseOrderReceiveID = stockdata[0].PurchaseOrderReceiveID;
            //    $("#SignStatus").val(datas[0].datastust);
            stockIn.SignStatus = stu;
            //    $("#AddStockDate").val(datas[0].AddStockDate);
            stockIn.AddStockDate = stockdata[0].AddStockDate;
            //    $("#Remark").val(datas[0].Remark);
            stockIn.Remark = stockdata[0].Remark;
            //    $("#CreateEmployeeID").val(datas[0].CreateEmployeeID);
            stockIn.CreateEmployeeID = stockdata[0].CreateEmployeeID;
            //    $("#CreateDate").val(datas[0].date);
            stockIn.CreateDate = stockdata[0].CreateDate;

            if (ModelState.IsValid)
            {
                db.Entry(stockIn).State = EntityState.Modified;
                db.SaveChanges();
            }
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PMSAWebMVC/Views/PurchaseOrderReceives/Create.cshtml
@model PMSAWebMVC.Models.PurchaseOrderReceive

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>PurchaseOrderReceive</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PurchaseOrderReceiveID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PurchaseOrderReceiveID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PurchaseOrderReceiveID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PurchaseOrderID, "PurchaseOrderID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PurchaseOrderID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PurchaseOrderID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PurchaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PurchaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PurchaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PurchaseEmployeeID, "PurchaseEmployeeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("PurchaseEmployeeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.PurchaseEmployeeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SupplierCode, "SupplierCode", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SupplierCode", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SupplierCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SupplierAccountID, "SupplierAccountID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SupplierAccountID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SupplierAccountID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SignStatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SignStatus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SignStatus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SignFlowOID, "SignFlowOID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SignFlowOID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SignFlowOID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PMSAWebMVC/Views/PurchaseOrderReceives/Index.cshtml
@model IEnumerable<PMSAWebMVC.Models.PurchaseOrderReceive>

@{
    ViewBag.Title = "進貨總表";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-table"></i>
        進貨總表
    </div>
    <div class="card-body">
        <div>
            <div style="float:right" id="dabtn"></div>
        </div>
        <div class="table-responsive">
            <br />
            <table class="table table-striped hover order-column nowrap text-left" id="dataTable" cellspacing="0" style="width:100%">
                <thead>
                    <tr class="bg-primary text-white text-center">
                        <th>@Html.DisplayNameFor(model => model.PurchaseOrderReceiveID)</th>
                        <th>@Html.DisplayNameFor(model => model.PurchaseOrderID)</th>
                        <th>廠商聯絡人</th>
                        <th>@Html.DisplayNameFor(model => model.SupplierInfo.SupplierName)</th>
                        <th>@Html.DisplayNameFor(model => model.SignStatus)</th>
                        <th>@Html.DisplayNameFor(model => model.PurchaseDate)</th>
                        <th style="width:10%;">編輯</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        string date1 = String.Format("{0:yyyy/MM/dd}", item.PurchaseDate);
                        string stuts = "";
                        switch (item.SignStatus)
                        {
                            case "Y":
                                stuts = "同意";
                                break;
                            case "N":
                                stuts = "拒絕";
                                break;
                            case "S":
                                stuts = "簽核中";
                                break;
                        }
                        <tr>
                            <td>@Html.DisplayFor(modelItem => item.PurchaseOrderReceiveID)</td>
                            <td>@Html.DisplayFor(modelItem => item.PurchaseOrderID)</td>
                            <td>@Html.DisplayFor(modelItem => item.SupplierAccount.ContactName)</td>
                            <td>@Html.DisplayFor(modelItem => item.SupplierInfo.SupplierName)</td>
                            <td id="cel01">@Html.DisplayFor(modelItem => stuts)</td>
                            <td>@Html.DisplayFor(modelItem => date1)</td>
                            <td class="table-data-feature">
                                <span data-toggle="modal" data-target=".bd-example-modal-lg">
                                    <button name="click03" class="btn btn-outline-secondary btn-icon" data-toggle="tooltip" title="檢視" data-dc="@item.PurchaseOrderReceiveID">
                                        <i class="far fa-eye"></i>
                                    </button>
                                </span>
                                <span data-toggle="modal" data-target=".bd-example-modal-lg">
                                    <button name="click04" class="btn btn-outline-secondary btn-icon" data-toggle="tooltip" title="簽核" data-dc="@item.PurchaseOrderReceiveID">
                                        <i class="far fa-edit"></i>
                                    </button>
                                </span>
                                <button class="btn btn-outline-secondary btn-icon" title="進貨明細">@Html.ActionLink(" ", "IndexDtl", new { id = item.PurchaseOrderReceiveID }, new { @class = "far fa-file-alt", @style = "color:rgb(160, 185, 185)" })</button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>


<style>
    .modal-header {
        padding: 15px;
        border-bottom: 1px solid #e5e5e5;
        background-color: blueviolet;
    }

    .modal-title {
        color: white;
    }

    .required:after {
        margin: 2px;
        content: '*';
        color: red;
    }

    #bt {
        border-style: none;
    }
</style>

@section scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script>
        var table = $('#dataTable').DataTable({
            buttons: [
                'excel', 'pdf'
            ]
        });
        $(document).ready(function () {
            table.buttons().container().appendTo($('.col-sm-6:eq(0)', table.buttons().container().appendTo($('#dabtn'))));
        });

        $('#myInput').on('keyup', function () {
            table.search(this.value).draw();
        });

        //檢視
        $(document).on('click', "button[name = 'click03']", function () {
            let id1 = this.dataset.dc;
            if(id1 == undefined){
                id1 = $(this).parents('tr').find('td:first-child').text();
            }
            $.getJSON("@Url.Action("Details", "PurchaseOrderReceives")/" + id1, function (datas) {
                $('#ModalTitle').text('檢視進貨總表');
                $('*[name="da"]').attr('disabled', true);
                $('*[name="dta"]').attr('disabled', true);
                $('*[name="daal"]').attr('disabled', true);
                $('#btnUpdate').hide();
                $('*[name=dal]').hide();
                $('*[name=dta]').show();
                $("#StockInID").val(datas[0].StockInID);
                $("#PurchaseOrderReceiveID").val(datas[0].PurchaseOrderReceiveID);
                $("#PurchaseOrderID").val(datas[0].PurchaseOrderID);
                $("#PurchaseDate").val(datas[0].date);
                $("#PurchaseEmployeeID").val(datas[0].emid1);
                $("#SupplierCode").val(datas[0].scode1);
                $("#SupplierAccountID").val(datas[0].supid1);
                $("#SignStatus").val(datas[0].datastust);
                $("#PurchaseEmployeeID01").val(datas[0].PurchaseEmployeeID);
                $("#SupplierCode01").val(datas[0].SupplierCode);
                $("#SupplierAccountID01").val(datas[0].SupplierAccountID);
            })
        });

        //更新
        var sein;
        $(document).on('click', "td", function () {
            var rowss = $(this).closest("tr");  //抓取列
            var celss = $(this).siblings("#cel01"); //抓取欄
            sein = table.row(rowss).cell(celss);
        })
        $(document).on('click', "button[name = 'click04']", function () {
            let id1 = this.dataset.dc;
            if(id1 == undefined){
                id1 = $(this).parents('tr').find('td:first-child').text();
            }
            $.getJSON("@Url.Action("Details", "PurchaseOrderReceives")/" + id1, function (datas) {
                $('#ModalTitle').text('簽核');
                $('*[name="da"]').attr('disabled', false);
                $('*[name="dta"]').attr('disabled', true);
                $('*[name="daal"]').attr('disabled', true);
                $('#btnUpdate').show();
                $('*[name=dal]').show();
                $('*[name=dta]').hide();
                $("#StockInID").val(datas[0].StockInID);
                $("#PurchaseOrderReceiveID").val(datas[0].PurchaseOrderReceiveID);
                $("#PurchaseOrderID").val(datas[0].PurchaseOrderID);
                $("#PurchaseDate").val(datas[0].date);
                $("#PurchaseEmployeeID").val(datas[0].emid1);
                $("#SupplierCode").val(datas[0].scode1);
                $("#SupplierAccountID").val(datas[0].supid1);
                $("#SignStatus").val(datas[0].datastust);
                $("#PurchaseEmployeeID01").val(datas[0].PurchaseEmployeeID);
                $("#SupplierCode01").val(datas[0].SupplierCode);
                $("#SupplierAccountID01").val(datas[0].SupplierAccountID);
            })
        });

        $('#btnUpdate').click(function () {
            var statusObj = {
                StockInID: $("#StockInID").val(),
                PurchaseOrderReceiveID: $("#PurchaseOrderReceiveID").val(),
                SignStatus: $("#SignStatus01").val(),
                PurchaseOrderID:$("#PurchaseOrderID").val(),
                PurchaseDate:$("#PurchaseDate").val(),
                PurchaseEmployeeID:$("#PurchaseEmployeeID01").val(),
                SupplierCode:$("#SupplierCode01").val(),
                SupplierAccountID:$("#SupplierAccountID01").val()
                }
                $.ajax({
                    url: '@Url.Action("Edit", "PurchaseOrderReceives")',
                    dataType: 'json',
                    type: 'POST',
                    contentType: 'application/json; charset=utf-8',
                    data: JSON.stringify(statusObj)
                }).done(function (response) {
                    if (response.status) {
                        toastr.success(response.message, "通知");
                        sein.data(response.datastust).draw(false);
                    }
                }).fail(function(response){
                    toastr.error(response.message, "警告");
                })
            $('#StockInModal').modal('hide');
        })

    </script>

}


<!--Modal-->
<div class="modal fade bd-example-modal-lg" id="StockInModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalTitle"></h5>
            </div>
            <div class="modal-body">
                <form id="addForm">
                    <div class="form-group" name="daal">
                        <label for="PurchaseOrderReceiveID">@Html.DisplayNameFor(model => model.PurchaseOrderReceiveID)</label>
                        <input type="text" class="form-control" id="PurchaseOrderReceiveID" name="daal">
                    </div>
                    <div class="form-group" name="dta">
                        <label for="PurchaseOrderID">@Html.DisplayNameFor(model => model.PurchaseOrderID)</label>
                        <br />
                        <input type="text" class="form-control" id="PurchaseOrderID" name="dta">
                    </div>
                    <div class="form-group" name="dta">
                        <label for="PurchaseEmployeeID">@Html.DisplayNameFor(model => model.PurchaseEmployeeID)</label>
                        <br />
                        <input type="text" class="form-control" id="PurchaseEmployeeID" name="dta">
                        <input style="display:none" type="text" class="form-control" id="PurchaseEmployeeID01" name="d">
                    </div>
                    <div class="form-group" name="dta">
                        <label for="SupplierCode" name="dta">進貨廠商</label>
                        <input type="text" class="form-control" id="SupplierCode" name="dta">
                        <input style="display:none" type="text" class="form-control" id="SupplierCode01" name="d">
                    </div>
                    <div class="form-group" name="dta">
                        <label for="SupplierAccountID">廠商聯絡人</label>
                        <br />
                        <input type="text" class="form-control" id="SupplierAccountID" name="dta">
                        <input style="display:none" type="text" class="form-control" id="SupplierAccountID01" name="d">
                    </div>
                    <div class="form-group" name="dta">
                        <label for="PurchaseDate">@Html.DisplayNameFor(model => model.PurchaseDate)</label>
                        <input type="text" class="form-control" id="PurchaseDate" name="dta">
                    </div>
                    <div class="form-group" name="daa">
                        <label for="SignStatus">@Html.DisplayNameFor(model => model.SignStatus)</label>
                        <input type="text" class="form-control" id="SignStatus" name="dta">
                        <select class="form-control" id="SignStatus01" name="dal">
                            <option value="S">簽核中</option>
                            <option value="Y">同意</option>
                            <option value="N">拒絕</option>
                        </select>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button id="btnClose" type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                <button id="btnUpdate" type="button" class="btn btn-success">修改</button>
            </div>
        </div>
    </div>
</div>