PMSAWebMVC/Models/SourceList.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMSAWebMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SourceList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SourceList()
        {
            this.InventoryDtl = new HashSet<InventoryDtl>();
            this.PurchaseOrderDtl = new HashSet<PurchaseOrderDtl>();
            this.PurchaseOrderDtlTemp = new HashSet<PurchaseOrderDtlTemp>();
            this.SourceListDtl = new HashSet<SourceListDtl>();
        }
    
        public int SourceListOID { get; set; }
        public string SourceListID { get; set; }
        public string PartNumber { get; set; }
        public int QtyPerUnit { get; set; }
        public Nullable<int> MOQ { get; set; }
        public int UnitPrice { get; set; }
        public string SupplierCode { get; set; }
        public int UnitsInStock { get; set; }
        public int UnitsOnOrder { get; set; }
        public Nullable<int> SafetyQty { get; set; }
        public Nullable<int> EXP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryDtl> InventoryDtl { get; set; }
        public virtual Part Part { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDtl> PurchaseOrderDtl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderDtlTemp> PurchaseOrderDtlTemp { get; set; }
        public virtual SupplierInfo SupplierInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SourceListDtl> SourceListDtl { get; set; }
    }
}

PMSAWebMVC/Controllers/SourceListsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PMSAWebMVC.Models;
using PMSAWebMVC.ViewModels.SourceLists;

namespace PMSAWebMVC.Controllers
{
    [Authorize(Roles = "Buyer, Manager, ProductionControl")]
    public class SourceListsController : BaseController
    {
        //Test//
        private PMSAEntities db = new PMSAEntities();
        //string SourceListID2;

        // GET: SourceLists貨源清單
        public ActionResult Index()
        {
            var sourceList = db.SourceList.Include(s => s.Part).Include(s => s.SupplierInfo);
            
            return View(sourceList);
        }


        public ActionResult Detail(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SourceList sourceList = db.SourceList.Find(id);
            if (sourceList == null)
            {
                return HttpNotFound();
            }
            var datas = from s in db.SourceList.AsEnumerable()
                        where  s.SourceListID==id
                        select new 
                        {
                            SourceListID = s.SourceListID,
                            PartNumber = s.PartNumber,
                            QtyPerUnit = s.QtyPerUnit,
                            MOQ = s.MOQ,
                            UnitPrice = s.UnitPrice,
                            SupplierCode = s.SupplierCode,
                            SupplierName = s.SupplierInfo.SupplierName,
                            UnitsInStock = s.UnitsInStock,
                            UnitsOnOrder = s.UnitsOnOrder,
                            SafetyQty = s.SafetyQty,
                            EXP = s.EXP

                        };
            var da = datas.ToList();
            return Json(datas, JsonRequestBehavior.AllowGet);
        }

        // GET: SourceLists/Create貨源清單新增畫面
        public ActionResult Create()
        {
            //var q=from p in db.SourceList select p.PartNumber

            ViewBag.PartNumber = new SelectList(db.Part, "PartNumber", "PartName");
            ViewBag.SupplierCode = new SelectList(db.SupplierInfo, "SupplierCode", "SupplierName");
            return View();
        }
  

        // POST: SourceLists/Create 貨源清單新增
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SourceListOID,SourceListID,PartNumber,QtyPerUnit,MOQ,UnitPrice,SupplierCode,UnitsInStock,UnitsOnOrder,SafetyQty,EXP")] SourceList sourceList)
        {
            if (ModelState.IsValid)
            {
                sourceList.UnitsInStock = 0;
                sourceList.UnitsOnOrder = 0;
                sourceList.SourceListID = sourceList.PartNumber + "-" + sourceList.SupplierCode;
                db.SourceList.Add(sourceList);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PartNumber = new SelectList(db.Part, "PartNumber", "PartName", sourceList.PartNumber);
            ViewBag.SupplierCode = new SelectList(db.SupplierInfo, "SupplierCode", "SupplierName", sourceList.SupplierCode);
            return View(sourceList);
        }



        //修改貨源清單
        [HttpPost]
        [AuthorizeDeny(Roles = "Manager")]
        public ActionResult Edit(SourceList sourceList)
        {
            string message = "修改成功!!";
            bool status = true;

            if (ModelState.IsValid)
            {
                db.Entry(sourceList).State = EntityState.Modified;
                db.SaveChanges();
                return Json(new { status = status, message = message, id = db.SourceList.Max(x => x.SourceListID) }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                message = "修改失敗!!";
                status = false;
                return Json(new { status = status, message = message }, JsonRequestBehavior.AllowGet);
            }
        }

        //貨源清單刪除
        [HttpPost]
        public ActionResult Delete(string id)
        {
            try
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                SourceList sourceList = db.SourceList.Find(id);
                if (sourceList == null)
                {
                    return HttpNotFound();
                }
                db.SourceList.Remove(sourceList);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return Content("<script> alert('刪除失敗');window.location.href='../Index'</script>");
            }

        }

        // POST: SourceLists/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(string id)
        //{
        //    SourceList sourceList = db.SourceList.Find(id);
        //    db.SourceList.Remove(sourceList);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }






/// <summary>
/// /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
/// </summary>
/// <returns></returns>







        //// GET: SourceListsDtl貨源清單明細
        //public ActionResult IndexDtl()
        //{
        //    var sourceListDtl = db.SourceListDtl.Include(s => s.SourceList);

            

        //    return View(sourceListDtl);
        //}

        //// GET: SourceListDtls/Details/5 貨源清單明細檢視畫面
        //public ActionResult DetailsDtl(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    SourceListDtl sourceListDtl = db.SourceListDtl.Find(id);
        //    if (sourceListDtl == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(sourceListDtl);
        //}


        public ActionResult DetailDtl(string id)
        {
            int idd = int.Parse(id);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SourceListDtl sourceListDtl = db.SourceListDtl.Find(idd);
            if (sourceListDtl == null)
            {
                return HttpNotFound();
            }
            var datas = from s in db.SourceListDtl.AsEnumerable()
                        where s.SourceListDtlOID == idd
                        select new
                        {
                            SourceListDtlOID = s.SourceListDtlOID,
                            SourceListID = s.SourceListID,
                            QtyDemanded = s.QtyDemanded,
                            Discount = s.Discount, //終極無敵霹靂轉換
                            //DiscountBeginDate = s.DiscountBeginDate,
                            DiscountBeginDate = Convert.ToDateTime(s.DiscountBeginDate.ToString()).ToString("yyyy/MM/dd"),
                            DiscountEndDate = Convert.ToDateTime(s.DiscountEndDate.ToString()).ToString("yyyy/MM/dd"),
                            CreateDate = s.CreateDate.ToString("yyyy/MM/dd")

                        };
            var da = datas.ToList();
            return Json(datas, JsonRequestBehavior.AllowGet);
        }

        // GET: SourceListDtls/Create貨源清單明細新增畫面
        public ActionResult CreateDtl()
        {
            ViewBag.SourceListID = new SelectList(db.SourceList, "SourceListID", "SourceListID");
            SourceListDtl s = new SourceListDtl();
            s.DiscountBeginDate = DateTime.Now;
            s.DiscountEndDate = DateTime.Now.AddDays(1);
            return View(s);
        }
        // GET: SourceListDtls/Create貨源清單明細新增畫面
        //[HttpPost]
        public ActionResult CreateDtl2(string id)
        {
            ViewBag.SourceListID = new SelectList(db.SourceList, "SourceListID", "PartNumber");
            ViewBag.SourceListIDD = id;

            SourceListDtl s = new SourceListDtl();
            s.SourceListID = id;
            s.DiscountBeginDate = DateTime.Now;
            s.DiscountEndDate = DateTime.Now.AddDays(1);
            return View(s);
            //ViewBag.PartNumber = new SelectList(db.Part, "PartNumber", "PartName");
            //ViewBag.SupplierCode = new SelectList(db.SupplierInfo, "SupplierCode", "SupplierName");
            //return View();
        }
        

        // POST: SourceListDtls/Create 貨源清單明細新增 失敗!!!!!!!!!!!!!!!
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateDtl([Bind(Include = "SourceListDtlOID,SourceListID,QtyDemanded,Discount,DiscountBeginDate,DiscountEndDate,CreateDate")] SourceListDtl sourceListDtl)
        {
            if (ModelState.IsValid)
            {
                sourceListDtl.CreateDate = DateTime.Now;
                db.SourceListDtl.Add(sourceListDtl);
                db.SaveChanges();
                return RedirectToAction("IndexDtl");
            }

            ViewBag.SourceListID = new SelectList(db.SourceList, "SourceListID", "PartNumber", sourceListDtl.SourceListID);
            return View(sourceListDtl);
        }

        // POST: SourceListDtls/Create 貨源清單明細新增 
        // 若要免於過量張貼攻擊，請啟用想要繫結的特定屬性，如需
        // 詳細資訊，請參閱 https://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]

PMSAWebMVC/Views/SourceLists/Createtest.cshtml
@model PMSAWebMVC.ViewModels.SourceLists.SourceListsCreateViewModel
@{
    ViewBag.Title = "新增貨源清單";
}

<h2>@ViewBag.Title</h2>




<div class="card mb-3">
    <div class="card-header">
        <i class="fab fa-wpforms"></i> 貨源清單
    </div>
    <div class="card-body">
        <div class="form-horizontal">
            <div class="form-group row">
                @Html.LabelFor(m => m.SelectedSupplierName, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-5 mb-4">
                    @Html.DropDownListFor(m => m.SelectedSupplierName, Model.SupplierList, "請選擇", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.SelectedSupplierName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                @Html.LabelFor(m => m.SelectedPartName, htmlAttributes: new { @class = "control-label col-md-3" })
                <div class="col-md-5 mb-4">
                    @Html.DropDownListFor(m => m.SelectedPartName, Model.PartList, "請選擇", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.SelectedPartName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="card-body mb-0 pb-0 pt-2 border-top-dashed mt-3">
                <div class="row">
                    <div class="col-md-3 col-6">
                        @Html.LabelFor(model => model.MOQ, htmlAttributes: new { @class = "control-label " })
                        @Html.EditorFor(model => model.MOQ, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MOQ, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-3 col-6">
                        @Html.LabelFor(model => model.QtyPerUnit, htmlAttributes: new { @class = "control-label " })
                        @Html.EditorFor(model => model.QtyPerUnit, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.QtyPerUnit, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-3 col-6">
                        @Html.LabelFor(model => model.EXP, htmlAttributes: new { @class = "control-label" })
                        @Html.EditorFor(model => model.EXP, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.EXP, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="card-body mb-0 pb-0 pt-2 border-top-dashed mt-3">
                <div class="row">
                    <div class="col-md-3 col-6">
                        @Html.LabelFor(model => model.SafetyQty, htmlAttributes: new { @class = "control-label " })
                        @Html.EditorFor(model => model.SafetyQty, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SafetyQty, "", new { @class = "text-danger" })
                    </div>
                    <div class="col-md-3 col-6">
                        @Html.LabelFor(model => model.UnitPrice, htmlAttributes: new { @class = "control-label " })
                        @Html.EditorFor(model => model.UnitPrice, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.UnitPrice, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>








<div class="card mb-3">
    <div class="card-header">
        <i class="fab fa-wpforms"></i> 貨源清單明細
    </div>
    <div class="card-body">
        <div class="card-body mb-0 pb-0 pt-2 border-top-dashed mt-3">
            <div class="row">
                <div class="col-md-3 col-6">
                    @Html.LabelFor(model => model.QtyDemanded, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.QtyDemanded, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.QtyDemanded, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3 col-6">
                    @Html.LabelFor(model => model.Discount, htmlAttributes: new { @class = "control-label " })
                    @Html.EditorFor(model => model.Discount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Discount, "", new { @class = "text-danger" })
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="form-group">
                        <label class="control-label " for="DiscountEndDate">@Html.DisplayNameFor(model => model.DiscountEndDate)</label>
                        <div class="input-group date" id="DiscountEndDate" data-target-input="nearest">
                            <input type="text" id="DiscountEndDate2" class="form-control datetimepicker-input" data-target="#DiscountEndDate" data-toggle="datetimepicker" name="da"/>
                            <div class="input-group-append" data-target="#DiscountEndDate" data-toggle="datetimepicker">
                                <div class="input-group-text">
                                    <i class="fa fa-calendar"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="form-group">
                        <label class="control-label " for="DiscountBeginDate">@Html.DisplayNameFor(model => model.DiscountEndDate)</label>
                        <div class="input-group date" id="DiscountBeginDate" data-target-input="nearest">
                            <input type="text" id="DiscountBeginDate2" class="form-control datetimepicker-input" data-target="#DiscountBeginDate" data-toggle="datetimepicker" name="da"/>
                            <div class="input-group-append" data-target="#DiscountBeginDate" data-toggle="datetimepicker">
                                <div class="input-group-text">
                                    <i class="fa fa-calendar"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>

<div class="form-group">
    <div class="d-flex justify-content-center">
        <button id="btnSubmit1" type="submit" class="btn btn-primary btn-block"><i class="far fa-paper-plane"></i>新增</button>
    </div>
</div>


@Html.AntiForgeryToken()
<div class="card mb-3">
    <div class="card-header">
        <i class="fas fa-list"></i> 貨源清單細項
    </div>
    <div class="card-body">
        @if (TempData["ErrorMessage"] != null)
        {
            <div class="alert alert-warning" id="warning">
                <a href="#" class="close" data-dismiss="alert">&times;</a>
                @TempData["ErrorMessage"]
            </div>
        }
        <div class="table-responsive" id="dataTablesContainer"></div>
    </div>
</div>

<div class="form-group">
    <div class="d-flex justify-content-center">
        @*@Html.ActionLink("完成", "CreatePR", null, new { @class = "btn btn-success btn-block" })*@
        <button id="btnSubmit2" type="button" class="btn btn-primary btn-block"><i class="far fa-paper-plane"></i>完成</button>
    </div>
</div>


@section scripts
{
    <script>
           $(document).ready(function () {
       getday()
        });


        $('#btnSubmit1').click(function () {//新增
            $.ajax({
                url: "@Url.Action("Creat", "SourceLists")",
                type: "get",
                data: {
                    SupplierCode: $("#SelectedSupplierName").val(),
                    PartNumber: $("#SelectedPartName").val(),
                    MOQ: $("#MOQ").val(),
                    QtyPerUnit: $("#QtyPerUnit").val(),
                    SafetyQty: $("#SafetyQty").val(),
                    UnitPrice: $("#UnitPrice").val(),
                    EXP: $("#EXP").val(),
                    DiscountBeginDate: $("#DiscountBeginDate2").val(),
                    Discount: $("#Discount").val(),
                    DiscountEndDate: $("#DiscountEndDate2").val(),
                    QtyDemanded: $("#QtyDemanded").val(),
                },
            }).done(function (result) {
                $("#dataTablesContainer").html(result);
                $("#warning").remove();
                $("#ProductNume").val($("#SelectedProductName").val());
                $('*[name="da"]').attr('disabled', true);
        $('#SelectedSupplierName').attr('disabled', true);
        $('#SelectedPartName').attr('disabled', true);
        $('#MOQ').attr('disabled', true);
        $('#UnitPrice').attr('disabled', true);
        $('#SafetyQty').attr('disabled', true);
        $('#QtyPerUnit').attr('disabled', true);
        $('#EXP').attr('disabled', true);
        $('*#sourceListDtlOID2').hide();$('*#sourceListDtlOID').hide();

                $("#btnSubmit").prop("disabled", false);
            }).fail(function (e) {
                alert(e.responseText);
            });
        });

        $('#btnSubmit2').click(function () {//完成
        $('*[name="da"]').attr('disabled', false);
        $('#SelectedSupplierName').attr('disabled', false);
        $('#SelectedPartName').attr('disabled', false);
        $('#MOQ').attr('disabled', false);
        $('#UnitPrice').attr('disabled', false);
        $('#SafetyQty').attr('disabled', false);
        $('#QtyPerUnit').attr('disabled', false);
        $('#EXP').attr('disabled', false);
        $("#warning").remove();$("#dataTablesContainer").remove();

        $("#SelectedSupplierName")[0].selectedIndex = 0;
        $("#SelectedPartName")[0].selectedIndex = 0;
        $("#MOQ").val(0);$("#UnitPrice").val(0);$("#SafetyQty").val(0);$("#QtyPerUnit").val(0);$("#EXP").val(0);

        $("#Discount").val(0.00);$("#QtyDemanded").val(0);
        getday()


        });

        function getday() { //取日期
             var d = new Date();
    var day = d.getDate();
    var month = d.getMonth() + 1;
    var year = d.getFullYear();
    if (day < 10) {
        day = "0" + day;
    }
    if (month < 10) {
        month = "0" + month;
    }
    var date = year+ "/" + month + "/" +  day;

        var mydate = new Date();
    var t=mydate.toLocaleString();
        $('#DiscountBeginDate').children("input").val(date);
        $('#DiscountEndDate').children("input").val(date);
        }





         //刪除
        $(document).on('click', "button[name = 'click01']", function () {
            var $this = $(this);
            var table = $('#dataTable').DataTable();
            let id1 = this.dataset.wc;
            if(id1 == undefined){
                id1 = $(this).parents('tr').find('td:first-child').text();
        $('*#sourceListDtlOID2').hide();$('*#sourceListDtlOID').hide();
            }
            Swal.fire({
                title: '確定要刪除 ?',
                text: "刪除後你將沒有機會後悔 !",
                type: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                cancelButtonText: '取消',
                confirmButtonText: '刪除'
            }).then((result) => {
                if (result.value) {

                    $.ajax({
                        url: `@Url.Action("DeleteDtl", "SourceLists")`,
                        type: 'POST',
                        data: { id: id1 }

                    }).done(function () {
                        Swal.fire(
                            '刪除成功 !',
                            '此資料已被刪除',
                            'success'
                        );
                        table.row($($this).parents('tr')).remove().draw();
                    }).fail(function () {
                            toastr.error("刪除失敗", "警告");
                        })
                    }
                })
        });



    </script>
}

PMSAWebMVC/Views/SourceLists/DetailsDtl.cshtml
@model PMSAWebMVC.Models.SourceListDtl

@{
    ViewBag.Title = "檢視貨源清單明細";
}

<h2>檢視貨源清單明細</h2>

<div>
    @*<h4>SourceListDtl</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.QtyDemanded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QtyDemanded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Discount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Discount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiscountBeginDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiscountBeginDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiscountEndDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiscountEndDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreateDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SourceList.PartNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SourceList.PartNumber)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("編輯", "EditDtl", new { id = Model.SourceListDtlOID }, new { @class = "btn btn-info" }) 
    @Html.ActionLink("返回", "IndexDtl",null, new { @class = "btn btn-info" })
</p>

PMSAWebMVC/Views/SourceLists/_CreateSLItemPartial.cshtml
@model PMSAWebMVC.ViewModels.SourceLists.SourceListsCreateViewModel



@Html.HiddenFor(m => m.SourceListID)
@Html.HiddenFor(m => m.SupplierCode)

<table class="table table-striped table-bordered" id="dataTable" cellspacing="0" style="width:100%">
    <thead>
        <tr>
            <th id="sourceListDtlOID2">@Html.DisplayNameFor(model => model.SourceListDtlOID)</th>
            <th>@Html.DisplayNameFor(model => model.SourceListID)</th>
            <th>@Html.DisplayNameFor(model => model.PartName)</th>
            <th>@Html.DisplayNameFor(model => model.SupplierName)</th>
            <th>@Html.DisplayNameFor(model => model.QtyDemanded)</th>
            <th>@Html.DisplayNameFor(model => model.Discount)</th>
            <th>@Html.DisplayNameFor(model => model.DiscountBeginDate)</th>
            <th>@Html.DisplayNameFor(model => model.DiscountEndDate)</th>
            <th>動作</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.SourceListsDtlSetVM.Count(); i++)
        {
        <tr>
            <td   id="sourceListDtlOID">
                @Html.DisplayFor(m => Model.SourceListsDtlSetVM.ElementAt(i).SourceListDtlOID)
            </td>
            <td>
                @Html.DisplayFor(m => Model.SourceListsDtlSetVM.ElementAt(i).SourceListID)
            </td>
            <td>
                @Html.DisplayFor(m => Model.SourceListsDtlSetVM.ElementAt(i).PartName)
            </td>
            <td>
                @Html.DisplayFor(m => Model.SourceListsDtlSetVM.ElementAt(i).SupplierName)
            </td>
            <td>
                @Html.DisplayFor(m => Model.SourceListsDtlSetVM.ElementAt(i).QtyDemanded)
            </td>
            <td>
                @Html.DisplayFor(m => Model.SourceListsDtlSetVM.ElementAt(i).Discount)
            </td>
            <td>
                @Html.DisplayFor(m => Model.SourceListsDtlSetVM.ElementAt(i).DiscountBeginDate)
            </td>
            <td>
                @Html.DisplayFor(m => Model.SourceListsDtlSetVM.ElementAt(i).DiscountEndDate)
            </td>
            <td>
                @*@using
            @Html.BeginForm("Deletetest", "PurchaseRequisitions",FormMethod.Post)*@
                @*@Html.ActionLink("刪除", "Deletetest", "SourceLists", new { id = Model.SourceListsDtlSetVM.ElementAt(i).SourceListID }, new { @class = "btn btn-info" })*@
                <button name="click01" type="button" data-toggle="modal" data-target=".bd-example-modal-lg" class="btn btn-outline-secondary btn-icon" title="刪除"  >
                    <i class="far fa-trash-alt"></i>
                </button>
            </td>
        </tr>
        }

    </tbody>
</table>